### ISSUE TITLE
Skylands Plus does not load under DEV 1.6.2 version of CraftBukkit

### ISSUE THREAD

**Issue by SmallSansSerif** [betterphp/SkylandsPlus#76]
I'm having trouble getting skylands plus to load in the new dev versions of 1.6.2. It worked with the dev versions of 1.6.1 btw.

16:46:36 [INFO] This server is running CraftBukkit version git-Bukkit-1.5.2-R1.0-22-gcea8f29-b2811jnks (MC: 1.6.2) (Implementing API version 1.6.2-R0.1-SNAPSHOT)

16:46:39 [WARNING] [Multiverse-Core] Failed to set the generator for world 'skyland' to 'SkylandsPlus': java.lang.NoClassDefFoundError: net/minecraft/server/v1_6_R1/World
16:46:39 [WARNING] [Multiverse-Core] This is a bug in the generator plugin, NOT a bug in Multiverse!

Last login: Wed Jul 10 16:46:09 on ttys001
$ /Users/ssommerfeld/Desktop/CraftBukkit\ 1.6.2/start_server.command ; exit;
16:46:36 [INFO] Starting minecraft server version 1.6.2
16:46:36 [INFO] Loading properties
16:46:36 [INFO] Default game type: SURVIVAL
16:46:36 [INFO] Generating keypair
16:46:36 [INFO] Starting Minecraft server on *:25565
16:46:36 [INFO] This server is running CraftBukkit version git-Bukkit-1.5.2-R1.0-22-gcea8f29-b2811jnks (MC: 1.6.2) (Implementing API version 1.6.2-R0.1-SNAPSHOT)
16:46:36 [INFO] [PermissionsEx] sql backend registered!
16:46:36 [INFO] [PermissionsEx] file backend registered!
16:46:36 [INFO] [PermissionsEx] PermissionEx plugin initialized.
16:46:37 [INFO] [SkylandsPlus] Loading SkylandsPlus v0.16-SNAPSHOT
16:46:37 [INFO] [PermissionsEx] Loading PermissionsEx v1.19.6
16:46:37 [INFO] [PermissionsEx] Initializing file backend
16:46:37 [INFO] Permissions file successfully reloaded
16:46:37 [INFO] [Multiverse-Core] Loading Multiverse-Core v2.5-b670
16:46:37 [INFO] [Modifyworld] Loading Modifyworld v1.19.6
16:46:37 [INFO] [Multiverse-Portals] Loading Multiverse-Portals v2.5-b696
16:46:37 [INFO] [WorldGuard] Loading WorldGuard v5.7.5
16:46:37 [INFO] [Multiverse-Inventories] Loading Multiverse-Inventories v2.5-b357
16:46:37 [INFO] [ChatManager] Loading ChatManager v1.19.1
16:46:37 [INFO] [SkylandsPlus] Enabling SkylandsPlus v0.16-SNAPSHOT
16:46:37 [INFO] Preparing level "cheerios1"
16:46:37 [INFO] Preparing start region for level 0 (Seed: -9083855855089804335)
16:46:37 [INFO] Preparing start region for level 1 (Seed: -9083855855089804335)
16:46:38 [INFO] Preparing start region for level 2 (Seed: -9083855855089804335)
16:46:38 [INFO] [PermissionsEx] Enabling PermissionsEx v1.19.6
16:46:38 [INFO] [PermissionsEx] Superperms support enabled.
16:46:38 [INFO] [PermissionsEx] v1.19.6 enabled
16:46:38 [INFO] [Multiverse-Core] Enabling Multiverse-Core v2.5-b670
16:46:38 [INFO] [Multiverse-Core] [AllPay] - Version 13.0 - using only an item based economy for Multiverse-Core v2.5-b670
16:46:38 [INFO] Preparing start region for level 3 (Seed: -1623774494)
16:46:39 [WARNING] [Multiverse-Core] Failed to set the generator for world 'skyland' to 'SkylandsPlus': java.lang.NoClassDefFoundError: net/minecraft/server/v1_6_R1/World
16:46:39 [WARNING] [Multiverse-Core] This is a bug in the generator plugin, NOT a bug in Multiverse!
